# These are supported funding model platforms

github: # [CodyKoInABox]
ko_fi: codykoinabox

# need to add
# thanks_dev: # Replace with a single thanks.dev username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
